#!/bin/bash
if [ "${DEBUG}" = "true" ]; then
  set -x
  set -e
fi

here="$(readlink -m $(dirname ${BASH_SOURCE[0]}))"
workspace=$(dirname ${here})
project_name=$(basename ${workspace})
image="${DEV_IMAGE:-archlinux:latest}"
dev_name="${DEV_NAME:-${project_name}-dev}"
user_id="${DEV_USER_ID:-$(id -ru)}"
user_name="${DEV_USER_NAME:-$(id -run)}"
group_id="${DEV_GROUP_ID:-$(id -rg)}"
group_name="${DEV_GROUP_NAME:-$(id -rgn)}"
app_dir="${APP_DIR:-/var/app}"
container_manager="${CONTAINER_MANAGER:-autodetect}"

declare -a allowed_container_manager=(
  "podman"
  "docker"
)

if [ "${container_manager}" = "autodetect" ]; then
  for c in "${allowed_container_manager[@]}"
  do
    if command -v "${c}" > /dev/null; then
      container_manager="${c}"
      break
    fi
  done
  if [ "${container_manager}" = "autodetect" ]; then
    echo "Cannot find any valid container managers"
    exit 1
  fi
else
  ! command -v "${container_manager}" > /dev/null && echo "${container_manager} is not executable" && exit 1
fi

function generate_container_file()
{
  cat << EOF > "Containerfile"
FROM archlinux:latest

ARG USER_ID
ARG USER_NAME
ARG GROUP_ID
ARG GROUP_NAME
ARG APP_DIR
ARG SHELL
ARG PS1_HEAD
ENV PS1_HEAD=\$PS1_HEAD
RUN yes | pacman -Sy unzip sudo
RUN groupadd --gid \$GROUP_ID \$GROUP_NAME
RUN useradd --gid \$GROUP_ID --shell \$SHELL --uid \$USER_ID --create-home \$USER_NAME
RUN echo "\$USER_NAME ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers
RUN mkdir -p \$APP_DIR
RUN chown \$USER_NAME:\$GROUP_NAME \$APP_DIR
USER \$USER_NAME
WORKDIR \$APP_DIR
RUN curl https://raw.githubusercontent.com/mtwtkman/mi/main/setup | sh -s
EOF
}

function build_container()
{
  eval "${container_manager} build \
    --rm \
    -t ${dev_name} \
    --build-arg APP_DIR="${app_dir}" \
    --build-arg USER_ID="${user_id}" \
    --build-arg USER_NAME="${user_name}" \
    --build-arg GROUP_ID="${group_id}" \
    --build-arg GROUP_NAME="${group_name}" \
    --build-arg SHELL="${SHELL}" \
    --build-arg PS1_HEAD=\"\e[1;33m[ ${dev_name}]\e[0m\" \
    ${here}"
}

function run_container()
{
  eval "${container_manager} run \
    --tty \
    --interactive \
    --userns=keep-id \
    --volume="${workspace}":"${app_dir}"\
    --user="${user_name}" \
    --name="${dev_name}" \
    "${dev_name}" \
    bash"
}

function create_container()
{
  eval "${contaienr_manager} create \
    --userns=keep-id \
    --volume="${workspace}":"${app_dir}"\
    --user="${user_name}" \
    --name="${dev_name}" \
    "${dev_name}" \
    bash"
}

function enter_container()
{
  eval "${container_manager} start ${dev_name}"
  eval "${container_manager} exec \
    --tty \
    --interactive \
    --detach-keys= \
    "${dev_name}" \
    bash"
}

function kill_container()
{
  eval "${container_manager} stop "${dev_name}" > /dev/null"
  eval "${container_manager} rm "${dev_name}" > /dev/null"
}

function remove_image()
{
  image_name="${1:-${dev_name}}"
  eval "${container_manager} rmi ${image_name} > /dev/null"
}

function rebuild_image()
{
  kill_container
  remove_image
  build_container
}

commit_image()
{
  image_name="${1}"
  container_id="$(eval "${container_manager} ps -a --filter name=${dev_name} --format {{.ID}}")"
  eval "${container_manager} commit ${container_id} ${image_name}"
}

tag_image()
{
  src="${1}"
  dest="${2}"
  eval "${container_manager} tag ${src} ${dest}"
}

update_image()
{
  temp_name="${dev_name}-commit-temp"
  commit_image "${temp_name}"
  kill_container
  remove_image
  tag_image "${temp_name}" "${dev_name}"
  remove_image "${temp_name}"
}

function usage()
{
  indent="  "
  echo "usage: devkit <command>"
  echo "These are some commands for manipulating your dev container depends on ${container_manager}"
  echo ""
  echo -e "${indent}init\t\t\tGenerate a Containerfile"
  echo -e "${indent}build\t\t\tCreate a dev container image named ${dev_name}"
  echo -e "${indent}run\t\t\tCreate and attach to a dev container named ${dev_name}"
  echo -e "${indent}create\t\tCreate a dev container named ${dev_name}"
  echo -e "${indent}enter\t\t\tAttach to a created dev container"
  echo -e "${indent}rerun\t\t\tRerun a new dev container after removing created container"
  echo -e "${indent}kill | destroy\tRemove a created dev container"
  echo -e "${indent}cleanup\t\tRemove a dev container image"
  echo -e "${indent}rebuild\t\tRebuild a dev container image"
  echo -e "${indent}reboot\t\tRebuild a dev container image and run it"
  echo -e "${indent}update\t\tUpdate a dev container image to current container state"
}
cmd=$1
shift
case "${cmd}" in
  init) generate_container_file;;
  build) build_container;;
  run) run_container;;
  create) create_container;;
  enter) enter_container;;
  rerun)
    kill_container
    run_container
    ;;
  kill|destroy) kill_container;;
  cleanup)
    kill_container
    remove_image
    ;;
  rebuild) rebuild_image;;
  reboot)
    rebuild_image
    run_container
    ;;
  update) update_image;;
  *)
    usage
    exit 0
    ;;
esac
